#define TIMER0_IRQ_HANDLER				TIMER0_IRQHandler  
#define TIMER0_INTERRUPT_NVIC_NAME		TIMER0_IRQn      

#define TIMER1_IRQ_HANDLER				TIMER1_IRQHandler
#define TIMER1_INTERRUPT_NVIC_NAME		TIMER1_IRQn

#define TRUE 				1
#define FALSE				0
